### ISSUE TITLE
People nearby feature not working

### ISSUE THREAD

**Issue by shom13** [forkgram/TelegramAndroid#166] opened 2023-08-03 10:25 UTC
I just installed forkgram and i am trying to use the people nearby feature that i used to view om telegram foss. But for some reason it cannot access location although i have enabled the sharing location permission. Any ideas where am i going wrong here. Thanks in advance

**Comment by rodrigoaguilera** [comment] 2023-08-17 16:44
I'd say this is a duplicate of #144

**Comment by shom13** [comment] 2023-08-18 04:26
Ok downloaded it directly from github seems to have resolved the issue. Thanks

**Closed as completed** 2023-08-18 04:27 UTC
