### ISSUE TITLE
Forced close when trying to open the side menu on Android 4.4.2

### ISSUE THREAD

**Issue by BahrawiElimi** [forkgram/TelegramAndroid#45] opened 2020-12-17 13:14 UTC
Telegram crashes when I try to open the side menu, either by dragging or by clicking on the three dashes above, and therefore I cannot access the Telegram settings. This problem also exists in the official version of Telegram. I hope the problem will be solved soon, thank you

**Comment by ghost** [comment] 2020-12-17 16:26
> This problem also exists in the official version of Telegram

So this issue doesn't belong here, since it's not a bug of the fork but a bug of the official app. You may consider closing it and reporting to the official Telegram stream

**Comment by BahrawiElimi** [comment] 2020-12-17 17:32
Yes, you have already reported via email support@telegram.org and the support page https://telegram.org/support, do you know other ways to inform Telegram itself?

**Comment by 23rd** [comment] 2020-12-17 22:56
> do you know other ways to inform Telegram itself?

You can download the official version of Telegram Beta for Android, reproduce the crash and send your report.

**Closed as completed** 2020-12-23 12:25 UTC
